### PR TITLE
Wallet Connection

### PR DESCRIPTION
**Pull request by Guilherme775**
This PR adds the integration with connectWallet from seabug-contracts.

Related Issue: https://github.com/mlabs-haskell/seabug-contracts/issues/36

Related PR: https://github.com/mlabs-haskell/seabug-contracts/pull/43

### CODE REVIEW

**Comment by Guilherme775** [comment]
@rynoV Not sure if that's the right branch that I should open the PR for, can you confirm this? also not sure about who should I assign to review PRs in this repo, feel free to assign more people if you want.

**Comment by rynoV** [comment]
@Guilherme775 I think @nrutledge probably knows more about the branches. Is this commit working for you though with https://github.com/mlabs-haskell/seabug-contracts/pull/43 ? I'm getting an error about the log level, I think this branch is out of date, probably needs https://github.com/mlabs-haskell/nft-marketplace/tree/neil/integrate-seabug-contracts merged into it

**Comment by Guilherme775** [comment]
@rynoV I fixed the logLevel error, I think that is better to have this in the .env like the other ones instead of having a mocked value.

**Review by samuelWilliams99 — APPROVED** [review]

**Review by nrutledge — APPROVED** [review]
LGTM

**Pull request merged**
